version: "3"

vars:
  VERSION: 0.0.1

tasks:
  dev:
    cmd: yarn run dev --host 0.0.0.0
  test:
    cmd: yarn run test:coverage --browser.headless
  test_watch:
    cmd: yarn run test:watch
  test_view:
    cmd: yarn vite preview --outDir test/unit --base /
  ### Build frontend
  build:
    dir: ./frontend
    cmds:
      - yarn
      - yarn run build --outDir ../dist/static
