# https://taskfile.dev

version: '3'

vars:
  VERSION: 0.0.1
  BUILD_TARGET:
    - windows

includes:
  backend:
    flatten: true
    dir: ./backend
    taskfile: ./backend
    vars:
      BUILD_TARGET: $BUILD_TARGET
  frontend:
    flatten: true
    dir: ./frontend
    taskfile: ./frontend
    vars:
      BUILD_TARGET: $BUILD_TARGET

tasks:
  ### Make directories
  make_dist:
    preconditions:
    cmds:
      - mkdir -p ./dist
    silent: true
  make_static:
    deps:
      - make_dist
    cmds:
      - mkdir -p ./dist/static
    silent: true
  make_folders:
    deps:
      - make_dist
      - make_static
  ### Build group
  build_win:
    desc: "Build package for windows"
    deps:
      - build_frontend_any
      - build_backend_win
  build_all:
    desc: "Build all targets: {{.BUILD_TARGET}}"
    deps:
      - build_frontend_any
      - build_backend_win
  ### Copy configs
  copy_config:
    deps:
      - make_folders
    cmd: cp ./backend/config.json ./dist/config.json
  ### Default tasks
  default:
    cmds:
      - task: make_folders
      - task: build_all
      - task: copy_config
      - echo "DONE"
    silent: true
