# https://taskfile.dev

version: '3'

vars:
  VERSION: 0.0.1

includes:
  backend:
    flatten: false
    dir: ./backend
    taskfile: ./backend
  frontend:
    flatten: false
    dir: ./frontend
    taskfile: ./frontend

tasks:
  setup:
    cmd: .devcontainer/postCreateCommand.sh
  dev:
    deps:
      - frontend:dev
      - backend:dev
  build:
    cmds:
      - task: build_{{OS}}
  ### Make directories
  make_dist:
    preconditions:
    cmds:
      - mkdir -p ./dist
    silent: true
  make_static:
    deps:
      - make_dist
    cmds:
      - mkdir -p ./dist/static
    silent: true
  make_folders:
    deps:
      - make_dist
      - make_static
  ### Build group
  build:
    desc: "Build package for windows"
    deps:
      - frontend:build
      - backend:build
  build_all:
    desc: "Build all targets: {{.BUILD_TARGET}}"
    deps:
      - frontend:build
      - backend:build_any
  ### Copy configs
  copy_config:
    deps:
      - make_folders
    cmd: cp ./backend/config.json ./dist/config.json
  ### Default tasks
  default:
    cmds:
      - task: make_folders
      - task: build_all
      - task: copy_config
      - echo "DONE"
    silent: true
