definitions:
  controller.FadeResult:
    properties:
      err:
        additionalProperties:
          type: string
        type: object
      result:
        type: string
    type: object
info:
  contact: {}
paths:
  /fade:
    post:
      consumes:
      - application/json
      description: Control a DXM using fade in/out
      parameters:
      - description: Name of DMX group
        in: query
        name: group
        required: true
        type: string
      - description: Name of DMX group
        in: query
        name: isIn
        type: boolean
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controller.FadeResult'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/controller.FadeResult'
      summary: Control a DMX
      tags:
      - DMX
  /hello:
    get:
      consumes:
      - application/json
      description: do ping
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: liveness probe
      tags:
      - Hello World
swagger: "2.0"
