basePath: /api/v1
host: localhost:8080
info:
  contact: {}
  description: For my frendz.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: DMX BOX
  version: "0.1"
paths:
  /hello:
    get:
      consumes:
      - application/json
      description: do ping
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: liveness probe
      tags:
      - Hello World
swagger: "2.0"
