name: DMX BOX Build action
run-name: Build process
on:
  push:
    paths:
      - backend/.version
jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: "ALL: Install Task"
        uses: go-task/setup-task@v2
      - name: "Frontend: Use Node.js"
        uses: actions/setup-node@v4
        with:
          node-version: "25.x"
      - name: "Frontend: Install dependencies"
        run: yarn --frozen-lockfile
        working-directory: ./frontend
      - name: "Backend: Setup Go"
        uses: actions/setup-go@v5
        with:
          go-version: 1.25.x
      - name: "Backend: Install dependencies"
        run: go get .
        working-directory: ./backend
      - name: "ALL: Run test"
        run: task test
      - name: "Setup test env"
        run: playwright install
        working-directory: ./frontend
      - name: Archive code test results
        uses: actions/upload-artifact@v4
        with:
          name: test-reports
          path: |
            frontend/test
            backend/test
      - name: "ALL: Build"
        run: task build_all
      - name: Archive code test results
        uses: actions/upload-artifact@v4
        with:
          name: build
          path: |
            dist