name: DMX BOX Build action
run-name: Build process
on:
  push:
    tags:
      - "v*"

jobs:
  Release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: "ALL: Install Task"
        uses: go-task/setup-task@v2
      - name: "Frontend: Use Node.js"
        uses: actions/setup-node@v4
        with:
          node-version: "25.x"
      - name: "Frontend: Enable corepack"
        run: corepack enable
      - name: "Frontend: Install dependencies"
        run: yarn --frozen-lockfile
        working-directory: ./frontend
      - name: "Backend: Setup Go"
        uses: actions/setup-go@v5
        with:
          go-version: 1.26.x
      - name: "Backend: Install dependencies"
        run: go get .
        working-directory: ./backend

      - name: "ALL: Write version"
        run: |
          echo ${{ github.ref_name }} > ./backend/.version
          echo $(jq '.version |= "${{ github.ref_name }}"' ./frontend/package.json) > ./frontend/package.json

      - name: "Frontend: Setup test env"
        run: |
          yarn playwright install
        working-directory: ./frontend

      - name: "Backend: Setup test env"
        run: |
          go install gotest.tools/gotestsum@latest
          go install github.com/boumenot/gocover-cobertura@latest
          go install github.com/medyagh/gopogh/cmd/gopogh@latest
          go install github.com/swaggo/swag/cmd/swag@latest
          sudo apt-get update && sudo apt-get install -y socat
        working-directory: ./backend

      - name: "Backend: Create virtual console"
        run: |
          sudo socat -d -d \
            pty,raw,echo=0,link=/dev/ttyUSB0,mode=666,group=dialout \
            pty,raw,echo=0,link=/dev/ttyUSB1,mode=666,group=dialout &
      - name: "ALL: Run test"
        run: task test

      - name: "Backend: Close console port"
        run: killall socat

      - name: "Archive code test results"
        id: test_result
        uses: actions/upload-artifact@v4
        with:
          name: test-reports
          path: |
            frontend/test
            backend/test

      - name: Generate Release note
        run: echo -e "Test result\n${{ steps.test_result.outputs.artifact-url }}" >
          ./RELEASE_NOTE

      - name: "ALL: Build"
        run: task build_all

      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1.1.4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          release_name: Release ${{ github.ref_name }}
          body_path: ./RELEASE_NOTE
          draft: false
          prerelease: false

      - name: Compress bundle
        run: |
          mkdir -p artifacts
          zip -r artifacts/build.zip dist/

      - name: Upload release Asset
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./artifacts/build.zip
          asset_name: dmxbox-${{ github.ref_name }}.zip
          asset_content_type: application/zip
